#!/bin/bash
GH_TOKEN=$1
PULL_REQ_FILE=$2
ISSUES_FILE=$3
UPDATE_NUM=$4

OUTPUT_HOME="WSO2-CARBON-UPDATE-4.4.0-$UPDATE_NUM"
SUPPORT_CARBON_APIMGT_HOME=$(printenv SUPPORT_CARBON_APIMGT_HOME)

JAGGERY_APPS="repository/deployment/server/jaggeryapps"
OUTPUT_HOME_JAGGERY_APPS=$OUTPUT_HOME/carbon.home/$JAGGERY_APPS
PULLS_DIR="pull-requests"
JIRAS_DIR="jiras"
GH_ISSUES_DIR="git-issues"
UPDATE_DESC=$OUTPUT_HOME/update-descriptor.yaml


test -d $OUTPUT_HOME && rm -r $OUTPUT_HOME
mkdir -p $OUTPUT_HOME_JAGGERY_APPS
mkdir -p $JIRAS_DIR
mkdir -p $PULLS_DIR
mkdir -p $GH_ISSUES_DIR


echo "update_number: $UPDATE_NUM" > $UPDATE_DESC
echo "platform_version: 4.4.0" >> $UPDATE_DESC
echo "platform_name: wilkes" >> $UPDATE_DESC
echo "applies_to: APIM 2.1.0" >> $UPDATE_DESC
echo "bug_fixes:" >> $UPDATE_DESC


# PRS=(276 294 297 293 280 285 298 299 286 300 301 302 303 305 288 279 283 284 292 295 289 290 296 304 309 298)
######################################################################################################################

function canProcess() {
    local filepath=$1
    local filename=$(basename $filepath)
    local dir=$(dirname $filepath)
    if [[ $dir =~ ^features.* ]]
    then
        if [[ $filename =~ .*\.json$|.*\.js$|.*\.jag$ ]]
        then
           echo true
           return
        fi
    fi
    echo false
}

function getDestination() {
    local filepath=$1
    local filename=$(basename $filepath)
    local dir=$(dirname $filepath)
    local destDir=$(echo $dir | sed -e 's/^features\/apimgt\/org\.wso2\.carbon\.apimgt\.[a-z]*\.feature\/src\/main\/resources\///g')
    echo "$destDir"/$filename
}

function copyWithDirsToDestination() {
    local srcFilepath=$1
    local destFilepath=$2
    local destDir=$(dirname $destFilepath)
    test -d $destDir || mkdir -p $destDir && cp $srcFilepath $destFilepath
}

function isJava() {
    local filename=$(basename $1)
    if [[ $filename =~ .*\.java$ ]]
    then
       echo true
       return
    fi
    echo false
}

function getJavaComp() {
    echo  "$1" | awk -F"/src/[a-z]*/java" '{print $1}' 
}


function isJiraIssue() {
    if [[ $1 =~ .*https://wso2.org/jira.* ]]; then
       echo true
       return
    fi
    echo false
}

function isGHIssue() {
    if [[ $1 =~ .*https://github.com/wso2.* ]]; then
       echo true
       return
    fi
    echo false
}

function getJiraIssueId() {
    local jiraId=$(echo $1 | awk -F"https://wso2.org/jira/browse/" '{print $2}')
    echo $jiraId
}

function getGithubIssueUrl() {
    local ghIssueUrl=$(echo $1 | awk -F"https://github.com/" '{print $2}')
    echo $ghIssueUrl
}

function getGithubIssueId() {
    local ghIssueId=$(echo $1 | awk -F"https://github.com/[a-zA-Z0-9_\\-]*/[a-zA-Z0-9_\\-]*/issues/" '{print $2}')
    echo $ghIssueId
}

#######################################################################################################################




echo "Processing issue urls - $ISSUES_FILE"
issueList=$(cat $ISSUES_FILE)
for i in $issueList; do
    echo $i
    if [[ $(isJiraIssue $i) == true ]]; then
        jiraId=$(getJiraIssueId $i)

        if [ -e "$JIRAS_DIR/$jiraId".json ]
        then
            true
        else
            echo "Getting content of $i" 
            curl "https://wso2.org/jira/rest/api/2/issue/$jiraId" > $JIRAS_DIR/$jiraId.json
        fi

        content=$(cat $JIRAS_DIR/$jiraId.json)
        issueSummary=$(echo $content | jq '.fields.summary' | tr -d '"')
        echo $jiraId": "$issueSummary
        echo "  "$jiraId": "$issueSummary >> $UPDATE_DESC

    elif [[ $(isGHIssue $i) == true ]]; then
        ghIssueId=$(getGithubIssueId $i)

        if [ -e "$GH_ISSUES_DIR/$ghIssueId".json ]
        then
            true
        else
            echo "Getting content of $i" 
            curl -H "Authorization: token $1" https://api.github.com/repos/$(getGithubIssueUrl $i) > $GH_ISSUES_DIR/$ghIssueId.json 
        fi

        content=$(cat $GH_ISSUES_DIR/$ghIssueId.json)
        issueSummary=$(echo $content | jq '.title' | tr -d '"')
        echo $i": "$issueSummary
        echo "  "$i": "$issueSummary >> $UPDATE_DESC
    else
        echo "Unsupported Issue-"$i
    fi
    echo
done

echo 'description: |' >> $UPDATE_DESC
echo '  This is a sample description. Please update.' >> $UPDATE_DESC
echo 'file_changes:' >> $UPDATE_DESC
echo '  added_files: []' >> $UPDATE_DESC
echo '  removed_files: []' >> $UPDATE_DESC
echo '  modified_files:' >> $UPDATE_DESC

######################################################################################################################


echo "Processing pull request urls - $PULL_REQ_FILE"
prList=$(cat $PULL_REQ_FILE)
for i in $prList; do
    pr=$(echo $i | awk -F"https://github.com/[a-zA-Z0-9_\\-]*/carbon-apimgt/pull/" '{print $2}' | awk -F"/" '{print $1}')
    PRS+=($pr)
done


echo "Extracted PR numbers : ${PRS[@]}"
echo

for i in ${PRS[@]}; do

    if [ -e "$PULLS_DIR/$i".json ]
    then
        true
    else
        echo "Getting content of $i" 
        curl -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/wso2-support/carbon-apimgt/pulls/$i/files > $PULLS_DIR/$i.json
    fi

    content=$(cat $PULLS_DIR/$i.json)
    length=$(echo $content | jq '. | length')

    for (( c=0; c<$length; c++ ))
    do
	    filename=$(echo $content | jq ".[$c].filename")
	    filesList+=($filename)
    done
done

sortedUniqueFiles=$(echo "${filesList[@]}" | tr ' ' '\n' | sort -u | tr '\"' ' ')

echo "## Listing all changed files ##"
for i in $sortedUniqueFiles; do
    echo $i
done

echo


echo "## Processing files ##"
for i in $sortedUniqueFiles; do
    echo "$i"
    if [[ $(canProcess $i) == true ]]
    then
        src=$SUPPORT_CARBON_APIMGT_HOME/$i
        dest=$OUTPUT_HOME_JAGGERY_APPS/$(getDestination $i)
        echo "- copying to $dest"
        copyWithDirsToDestination $src $dest
        echo "  - $JAGGERY_APPS/$(getDestination $i)" >> $UPDATE_DESC
    else
        echo "- Ignored"
        if [[ $(isJava $i) == true ]]
        then
            javaComp=$(getJavaComp $i)
            javaCompList+=($javaComp)
        fi
    fi
    echo
done

echo
echo "$OUTPUT_HOME"
echo "======================"
tree $OUTPUT_HOME
echo
echo "update-descriptor.yaml"
echo "======================"
cat $UPDATE_DESC
echo

sortedUniqueJavaComps=$(echo "${javaCompList[@]}" | tr ' ' '\n' | sort -u | tr '\"' ' ')
echo "## Following java component jars needs to be manually copied ##"
for i in $sortedUniqueJavaComps; do
    echo $i
done

echo "## Finished ##"
